[versions]
kotlin = "1.9.23"
compose = "1.6.10"
buildconfig = "5.3.5"
detekt = "1.23.6"

[plugins]
kotlin-mpp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }

[libraries]
detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
